### ISSUE TITLE
Change bars(on the left)'s background color

### ISSUE THREAD

**Issue by jmnyarega** [codingedward/ailing-planet#2]
- The bars on the left for the different countries would also be awesome if they're different colours or shades of colour as opposed to all red

**Comment by codingedward** [comment]
I think you had also mentioned this earlier and seeing it coming from another person means it is something we really need to consider fixing. Maybe we could just have them in white with black text? I'm curious what you would suggest we do 👍

**Comment by jmnyarega** [comment]
That will be interesting. Will play around with the colors

**Comment by jmnyarega** [comment]
I think red should be preserved as a dominant colour,  we can try different shades of red 
![pic-selected-201015-1301-54](https://user-images.githubusercontent.com/20610060/96109888-d8a72900-0ee7-11eb-9977-cef5d3bb676d.png)
