### ISSUE TITLE
Background color of the globe

### ISSUE THREAD

**Issue by jmnyarega** [codingedward/ailing-planet#3]
The background colour of the globe should be a different colour from the spikes I think or a different shade of red.

**Comment by codingedward** [comment]
Interestingly, the bars are currently a different shade of red 😅 . The bars are completely red, using `#ff0000` while the globe is set to `rgb(0.6*255, 0, 0)`. Since the globe color is just for atmospheric setting, maybe we could reduce it to a lower shade of red, maybe like `#440000`.
