### ISSUE TITLE
Add a signifier to click on the map

### ISSUE THREAD

**Issue by jmnyarega** [codingedward/ailing-planet#4]
- Add a tip that one can click on a country on the map and see the trajectory of cases.

**Comment by codingedward** [comment]
This sounds great! 

To avoid having a distracting message continually, maybe they could have an option to dismiss this message by having the user click a "Got it!" button. Since we don't have a server, we could just save this on local storage.

**Comment by jmnyarega** [comment]
It took some time for me to discover this awesome feature too 😄 

Another solution will be to auto-select a country on the map by default(a country with the highest deaths or cases)

**Comment by codingedward** [comment]
Totally! I kind of prefer the message, since it is explicit and guarantees that the user knows what to do 👍

**Comment by jmnyarega** [comment]
Agreed, the message will be more explicit
